" --- General settings
set nocompatible
syntax enable
filetype plugin indent on
set tabstop=4
set shiftwidth=2
set expandtab
set mouse=a
set number
set relativenumber
set gdefault
set shortmess+=A
set autoindent
set cc=100
set backspace=indent,eol,start
set noautochdir

" --- Remaps
" Ctrl+s to save
nnoremap <c-s> :w<CR> 
inoremap <c-s> <Esc>:w<CR>
vnoremap <c-s> <Esc>:w<CR>

" Ctrl+q to quit tab
map <C-Q> :bd<CR>

nnoremap <space>qq :qa!<CR>
nnoremap q :q<CR>

" Indentation
nnoremap <TAB> >>
nnoremap <S-TAB> <<
vnoremap <TAB> >gv
vnoremap <S-TAB> <gv
nnoremap <A-v> <c-v>

" Substitute
nmap s :%s/

" Goto begin or end of line
nnoremap H ^
nnoremap L $

" Move line
nnoremap <M-j> :m .+1<CR>==
nnoremap <M-k> :m .-2<CR>==
inoremap <M-j> <Esc>:m .+1<CR>==gi
inoremap <M-k> <Esc>:m .-2<CR>==gi
vnoremap <M-j> :m '>+1<CR>gv=gv
vnoremap <M-k> :m '<-2<CR>gv=gv

"Split buffers
nnoremap <space>s :vsp<CR>

"Remove hightlights
nnoremap <space>h :noh<CR>

"auto close {
function! s:CloseBracket()
    return "{\<Enter>}\<Esc>O"
endfunction

function! s:CloseSBracket()
    return "[\<Enter>]\<Esc>O"
endfunction

function! s:ClosePar()
    return "(\<Enter>)\<Esc>O"
endfunction

inoremap <expr> {<Enter> <SID>CloseBracket()
inoremap <expr> [<Enter> <SID>CloseSBracket()
inoremap <expr> (<Enter> <SID>ClosePar()

" Vim hardmode !
for key in ['<Up>', '<Down>', '<Left>', '<Right>']
  exec 'noremap' key '<Nop>'
  exec 'inoremap' key '<Nop>'
  exec 'cnoremap' key '<Nop>'
endfor

" Upload visual selection to ix.io
vnoremap <space>u :w !curl -F "f:1=<-" ix.io<CR>

set t_fd=
set t_fe=
