" --- General settings
set nocompatible
syntax enable
filetype plugin indent on
set expandtab
set mouse=a
set number
set relativenumber
set gdefault
set shortmess+=A
set autoindent
set cc=100
set backspace=indent,eol,start
set noautochdir
colorscheme onedark

" --- Remaps
" Ctrl+s to save
nnoremap <c-s> :w<CR> 
inoremap <c-s> <Esc>:w<CR>
vnoremap <c-s> <Esc>:w<CR>

" Ctrl+q to quit tab
map <C-Q> :bd<CR>

nnoremap <space>qq :qa!<CR>
nnoremap q :q<CR>

" Indentation
nnoremap <TAB> >>
nnoremap <S-TAB> <<
vnoremap <TAB> >gv
vnoremap <S-TAB> <gv
nnoremap <A-v> <c-v>

" Substitute
nmap s :%s/

" Goto begin or end of line
nnoremap H ^
nnoremap L $

" Move line
nnoremap <M-j> :m .+1<CR>==
nnoremap <M-k> :m .-2<CR>==
inoremap <M-j> <Esc>:m .+1<CR>==gi
inoremap <M-k> <Esc>:m .-2<CR>==gi
vnoremap <M-j> :m '>+1<CR>gv=gv
vnoremap <M-k> :m '<-2<CR>gv=gv

"Split buffers
nnoremap <space>s :vsp<CR>

"Remove hightlights
nnoremap <space>h :noh<CR>

" Upload visual selection to ix.io
vnoremap <space>u :w !curl -F "f:1=<-" ix.io<CR>

set t_fd=
set t_fe=
