export PYTHON_HOST_PROG='/usr/sbin/python'
export PYTHON3_HOST_PROG='/usr/sbin/python3'
export ZSH="$HOME/.oh-my-zsh"
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

ZSH_THEME="robbyrussell"

plugins=(
	git
	web-search
)

alias vim="nvim"
alias vi="nvim"
alias lzd="lazydocker"
alias msbr="mvn spring-boot:run"
alias msbrd="mvn spring-boot:run -Dspring-boot.run.jvmArguments=\"-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005\""
alias mci="mvn clean install"
alias mcis="mvn clean install -DskipTests"
alias mt="mvn test"
alias mtd="mvn -Dmaven.surefire.debug test"
alias gdh="git diff HEAD"
alias dcu="docker-compose up"
alias dcud="docker-compose up -d"
alias ix="curl -F 'f:1=<-' ix.io"
alias lg="lazygit"
alias grbr="gradle bootRun"
alias grbrd="gradle bootRun --debug-jvm"

# enable control-s and control-q
stty start undef
stty stop undef
setopt noflowcontrol

source $ZSH/oh-my-zsh.sh

source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh

export DISPLAY=192.168.103.29:0
export LIBGL_ALWAYS_INDIRECT=1

RUNNING=`ps aux | grep dockerd | grep -v grep`
if [ -z "$RUNNING" ]; then
  sudo dockerd > /dev/null 2>&1 &
  disown
fi
